Split rows into chunks of 5 due to Slack limit
```
Error:   web-api:WebClient:0 no more than 10 items allowed [json-pointer:/blocks/1/fields]
Error: Error: An API error occurred: invalid_blocks
```